# Generated by Django 5.1.6 on 2025-03-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.CharField(choices=[('active', 'Активное'), ('completed', 'Завершенное')], default='active', max_length=10),
        ),
    ]
