# Generated by Django 5.1.6 on 2025-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='messages',
            name='latitude',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='messages',
            name='longitude',
            field=models.FloatField(default='0'),
        ),
    ]
