# Generated by Django 5.1.6 on 2025-03-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_delete_location_messages_latitude_messages_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='latitude',
            field=models.FloatField(default='0', verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='longitude',
            field=models.FloatField(default='0', verbose_name='Долгота'),
        ),
    ]
