# Generated by Django 5.1.6 on 2025-03-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_messages_latitude_alter_messages_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='latitude',
            field=models.FloatField(default='0.0', verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='longitude',
            field=models.FloatField(default='0.0', verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='title',
            field=models.CharField(choices=[('Fire', 'Пожар'), ('Fire in the forest', 'Пожар в лесу'), ('Road repairs', 'Ремонт дорог'), ('Clean garbage', 'Убрать мусор'), ('Street light', 'Уличное освещение'), ('Other', 'Другое')], default='Other', max_length=50, verbose_name='Тема'),
        ),
    ]
