# Generated by Django 5.1.6 on 2025-04-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_messages_latitude_alter_messages_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='title',
            field=models.CharField(choices=[('Choose theme', 'Выберите тему'), ('Fire', 'Пожар'), ('Fire in the forest', 'Пожар в лесу'), ('Road repairs', 'Ремонт дорог'), ('Clean garbage', 'Убрать мусор'), ('Street light', 'Уличное освещение'), ('Other', 'Другое (пожалуйста напишите в первой строчке вашу тему)')], default='Choose theme', max_length=50, verbose_name='Тема'),
        ),
    ]
