# Generated by Django 5.1.6 on 2025-04-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_alter_messages_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='mes_text',
            field=models.TextField(max_length=500, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='title',
            field=models.CharField(choices=[('Choose theme', 'Выберите тему'), ('Fire', 'Пожар'), ('Fire in the forest', 'Пожар в лесу'), ('Road repairs', 'Ремонт дорог'), ('Clean garbage', 'Убрать мусор'), ('Street light', 'Уличное освещение'), ('Other', 'Смотрите тему ниже')], default='Choose theme', max_length=50, verbose_name='Тема'),
        ),
    ]
