# Generated by Django 5.1.6 on 2025-04-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_alter_messages_mes_text_alter_messages_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='created_at',
        ),
    ]
