# Generated by Django 5.1.6 on 2025-04-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_messages_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='created_at',
        ),
    ]
